### ISSUE TITLE
Notizen direkt bei der Aufgabe

### ISSUE THREAD

**Issue by kleinlain** [nyceapps/ChoreRallye#10]
beim Anlegen von neuen Aufgaben wäre es toll über einen Switch zu bestimmen ob bei D&D der Aufgabe direkt ein Notizfenster aufgehen soll.

(Hintergrund: auf diese Weise kann man z.B. für Einkäufe direkt den Preis angeben und wird bei simplen Tasks wie putzen, o.ä. nicht belästigt)

**Comment by nyceapps** [comment]
Enthalten in 0.7.3b

**Comment by nyceapps** [comment]
Teste mal

**Comment by kleinlain** [comment]
not as intended! :p
