### ISSUE TITLE
Undo?

### ISSUE THREAD

**Issue by kleinlain** [nyceapps/ChoreRallye#13]
Ich habe gerade gemerkt, dass "Abbruch" bei der Eingabe einer Notiz nur die Notiz nicht setzt, aber die Aufgabe.
Gibt es eine Undo Möglichkeit, im Sinne von "ups, verklickt, ich hab gar nicht geputzt, ich hab doch den Müll rausgebracht?"

**Comment by nyceapps** [comment]
Das geht auf zwei Arten:
- Oben in der Toolbar der Rückwärtspfeil löscht Schritt für Schritt Deine lokalen Eingaben
- In der History kannst Du mit Swipe nach rechts Einträge löschen
